### ISSUE TITLE
Feedly Dark usercss error

### ISSUE THREAD

**Issue by joxon** [daannorris/dark-themes#1]
https://github.com/daannorris/dark-themes/blob/a9b060007084126d766c28b651d4163d5fe1c1da/feedly-dark.user.css#L2

[this link](https://raw.githubusercontent.com/daannorris/dark-themes/master/feedly-dark.user.css) correctly points to the feedly dark usercss, but the usercss file is actually the one for WhatsApp.

**Comment by daannorris** [comment]
Yeah, im sorry, reversed #33d1aad04dbb65dcbad4ba8f802f7efb2a5273fd
